### ISSUE TITLE
打开后报错什么问题？ TypeError: Cannot read property 'aceEditor' of null

### ISSUE THREAD

**Issue by GitCod-Man** [Here21/aircraft-war#1]
您好，我用creator v1.4.2 打开后报错，不能打开 
 TypeError: Cannot read property 'aceEditor' of null
at _confirmClose (file:///F:/cocos/2017/creator/CocosCreator/resources/app.asar/builtin/code-editor/panel/page.js:19:28)
at window.addEventListener.event (file:///F:/cocos/2017/creator/CocosCreator/resources/app.asar/builtin/code-editor/panel/page.js:172:15)
  Class "ufoG" used by component "9ed9f/6UllKjIZCU2qyzWUA" in scene "Game.fire" is missing or invalid. Detailed information:
2
  Script attached to "infiniteBullet" in prefab "infiniteBullet.prefab" is missing or invalid. Detailed information:
  Script attached to "finiteBullet" in prefab "finiteBullet.prefab" is missing or invalid. Detailed information:
  Script attached to "enemy2" in prefab "enemy2.prefab" is missing or invalid. Detailed information:
  Script attached to "enemy1" in prefab "enemy1.prefab" is missing or invalid. Detailed information:
  Script attached to "enemy3" in prefab "enemy3.prefab" is missing or invalid. Detailed information:
  Script attached to "doubleBullet" in prefab "doubleBullet.prefab" is missing or invalid. Detailed information:
  Script attached to "tnt" in prefab "tnt.prefab" is missing or invalid. Detailed information:

属性检查器
TypeError: Cannot read property 'aceEditor' of null

**Comment by Here21** [comment]
请问是什么系统？尝试升级到最新的ccc可以解决吗？
